In [1]:
import pandas as pd

In [2]:
df = pd.read_clipboard(sep = '\\s{3}')
df

                         英文全称\t中文全称
0                   0\tAlaska 阿拉斯加州
1                 1\tArizona\t亚利桑那州
2                 2\tArkansas\t阿肯色州
3             3\tCalifornia\t加利福尼亚州
4                4\tColorado\t科罗拉多州
5             5\tConnecticut\t康涅狄格州
6                 6\tDelaware\t特拉华州
7                 7\tFlorida\t佛罗里达州
8                  8\tGeorgia\t佐治亚州
9                   9\tHawaii\t夏威夷州
10                  10\tIdaho\t爱达华州
11               11\tIllinois\t伊利诺州
12               12\tIndiana\t印地安那州
13                   13\tIowa\t艾奥瓦州
14                 14\tKansas\t堪萨斯州
15               15\tKentucky\t肯塔基州
16            16\tLouisiana\t路易斯安那州
17                   17\tMaine\t缅因州
18               18\tMaryland\t马里兰州
19         19\tMassachusetts\t麻萨诸塞州
20               20\tMichigan\t密歇根州
21             21\tMinnesota\t明尼苏达州
22           22\tMississippi\t密西西比州
23               23\tMissouri\t密苏里州
24                24\tMontana\t蒙大拿州
25             25\tNebraska\t内布拉斯加州
26                 26\tNevada\t内华达州
27        27\tNew Hampshire\t新罕布什尔州
28              28\tNewJersey\t新泽西州
29            29\tNew Mexico\t新墨西哥州
30                 30\tNewYork\t纽约州
31       31\tNorth Carolina\t北卡罗来纳州
32          32\tNorth Dakota\t北达科他州
33                   33\tOhio\t俄亥俄州
34             34\tOklahoma\t俄克拉何马州
35                 35\tOregon\t俄勒冈州
36         36\tPennsylvania\t宾夕法尼亚州
37           37\tRhode Island\t罗得岛州
38       38\tSouth Carolina\t南卡罗来纳州
39          39\tSouth Dakota\t南达科他州
40              40\tTennessee\t田纳西州
41                 41\tTexas\t得克萨斯州
42                    42\tUtah\t犹他州
43                43\tVermont\t佛蒙特州
44              44\tVirginia\t弗吉尼亚州
45             45\tWashington\t华盛顿州
46        46\tWest Virginia\t西弗吉尼亚州
47             47\tWisconsin\t威斯康星州
48                48\tWyoming\t怀俄明州
49  49\tWashington D.C.\t 华盛顿哥伦比亚特区

In [3]:
import os
df.to_excel('美国五十州中英文.xlsx')
os.startfile('美国五十州中英文.xlsx')

In [12]:
df['中文全称'] = df['中文全称'].str.strip()
df['中文全称']

0         阿拉斯加州
1         亚利桑那州
2          阿肯色州
3        加利福尼亚州
4         科罗拉多州
5         康涅狄格州
6          特拉华州
7         佛罗里达州
8          佐治亚州
9          夏威夷州
10         爱达华州
11         伊利诺州
12        印地安那州
13         艾奥瓦州
14         堪萨斯州
15         肯塔基州
16       路易斯安那州
17          缅因州
18         马里兰州
19        麻萨诸塞州
20         密歇根州
21        明尼苏达州
22        密西西比州
23         密苏里州
24         蒙大拿州
25       内布拉斯加州
26         内华达州
27       新罕布什尔州
28         新泽西州
29        新墨西哥州
30          纽约州
31       北卡罗来纳州
32        北达科他州
33         俄亥俄州
34       俄克拉何马州
35         俄勒冈州
36       宾夕法尼亚州
37         罗得岛州
38       南卡罗来纳州
39        南达科他州
40         田纳西州
41        得克萨斯州
42          犹他州
43         佛蒙特州
44        弗吉尼亚州
45         华盛顿州
46       西弗吉尼亚州
47        威斯康星州
48         怀俄明州
49    华盛顿哥伦比亚特区
Name: 中文全称, dtype: object

In [14]:
df.columns

Index(['英文全称 ', '中文全称'], dtype='object')

In [16]:
a = [i.strip() for i in df.columns.to_list()]
a

['英文全称', '中文全称']

In [17]:
df.columns = a
df.columns

Index(['英文全称', '中文全称'], dtype='object')

In [18]:
df['英文全称'] = df['英文全称'].str.strip()
df['英文全称']

0              Alaska
1             Arizona
2            Arkansas
3          California
4            Colorado
5         Connecticut
6            Delaware
7             Florida
8             Georgia
9              Hawaii
10              Idaho
11           Illinois
12            Indiana
13               Iowa
14             Kansas
15           Kentucky
16          Louisiana
17              Maine
18           Maryland
19      Massachusetts
20           Michigan
21          Minnesota
22        Mississippi
23           Missouri
24            Montana
25           Nebraska
26             Nevada
27      New Hampshire
28          NewJersey
29         New Mexico
30            NewYork
31     North Carolina
32       North Dakota
33               Ohio
34           Oklahoma
35             Oregon
36       Pennsylvania
37       Rhode Island
38     South Carolina
39       South Dakota
40          Tennessee
41              Texas
42               Utah
43            Vermont
44           Virginia
45         Washington
46      West Virginia
47          Wisconsin
48            Wyoming
49    Washington D.C.
Name: 英文全称, dtype: object

In [19]:
df

               英文全称       中文全称
0            Alaska      阿拉斯加州
1           Arizona      亚利桑那州
2          Arkansas       阿肯色州
3        California     加利福尼亚州
4          Colorado      科罗拉多州
5       Connecticut      康涅狄格州
6          Delaware       特拉华州
7           Florida      佛罗里达州
8           Georgia       佐治亚州
9            Hawaii       夏威夷州
10            Idaho       爱达华州
11         Illinois       伊利诺州
12          Indiana      印地安那州
13             Iowa       艾奥瓦州
14           Kansas       堪萨斯州
15         Kentucky       肯塔基州
16        Louisiana     路易斯安那州
17            Maine        缅因州
18         Maryland       马里兰州
19    Massachusetts      麻萨诸塞州
20         Michigan       密歇根州
21        Minnesota      明尼苏达州
22      Mississippi      密西西比州
23         Missouri       密苏里州
24          Montana       蒙大拿州
25         Nebraska     内布拉斯加州
26           Nevada       内华达州
27    New Hampshire     新罕布什尔州
28        NewJersey       新泽西州
29       New Mexico      新墨西哥州
30          NewYork        纽约州
31   North Carolina     北卡罗来纳州
32     North Dakota      北达科他州
33             Ohio       俄亥俄州
34         Oklahoma     俄克拉何马州
35           Oregon       俄勒冈州
36     Pennsylvania     宾夕法尼亚州
37     Rhode Island       罗得岛州
38   South Carolina     南卡罗来纳州
39     South Dakota      南达科他州
40        Tennessee       田纳西州
41            Texas      得克萨斯州
42             Utah        犹他州
43          Vermont       佛蒙特州
44         Virginia      弗吉尼亚州
45       Washington       华盛顿州
46    West Virginia     西弗吉尼亚州
47        Wisconsin      威斯康星州
48          Wyoming       怀俄明州
49  Washington D.C.  华盛顿哥伦比亚特区

In [20]:
df.to_excel('美国五十州中英文.xlsx',index = False)
os.startfile('美国五十州中英文.xlsx')